### ISSUE TITLE
css bug: page too wide

### ISSUE THREAD

**Issue by eelfroth** [Rotonde/rotonde-client#101]
regardless of window size, the page can always be scrolled left and right by a few percent.
this is quite annoying when scrolling with a touchpad…
not sure how to fix this, so making an issue

**Comment by neauoire** [comment]
I don't have side scrolls, but you can remove them by adding `overflow-x:hidden` to the body.

**Comment by eelfroth** [comment]
ok, if no one else has this I can just add that to my custom.css
leaving this open for now to wait for further reports

**Comment by lech** [comment]
Probably a CSS bug, I've noticed this as well when running rotonde client/portal out of the box. Mixed measurements might be the culprit.

**Comment by eelfroth** [comment]
this issue doesn't persist in the newest version. closing.
