### ISSUE TITLE
Mentions not working

### ISSUE THREAD

**Issue by dcposch** [Rotonde/rotonde-client#102]
Client version: 0.1.68
Beaker version: 0.7.7
URL to reproduce: dat://beddfd47e26d685d075410d16ed68fecbad686b837005f5dc8082fa9bae78cff/#mentions

my Rotonde portal says I have three mentions, but when I click on that tab I get nothing:

![image](https://user-images.githubusercontent.com/169280/32521715-77550238-c3c9-11e7-88a3-22c2d57cf2c0.png)

there are no exceptions in the console, but there are a few "connection failed" messages:

![image](https://user-images.githubusercontent.com/169280/32521791-c0351d6c-c3c9-11e7-8ded-bdd4a6702206.png)

**Comment by dcposch** [comment]
rotonde is amazing btw. i love the minimalist aesthetic

@neauoire

**Comment by eelfroth** [comment]
yeah I've noticed it broke again… I'm on it!

**Comment by 0x0ade** [comment]
I've noticed that we're counting the mentions separately from all other entries... and that the "Entries" tab number counts "invisible" entries, too.

In `feed.js`, we could update the `for(id in sorted_entries){` to count all visible entries (f.e. `c_all` or short, `ca`) and make the "Entries" tab use that instead. Something similar could be applied for mentions to only count "visible" mentions. This would mean that right now, something's either wrong with the mention filtering, or with how mentions are counted.

(By the way, I'm supporting your comment. Rotonde really is amazing!)

**Comment by eelfroth** [comment]
`for(id in sorted_entries){` is stopping after 40 entries though: `if(c > 40){ break; }`

**Comment by 0x0ade** [comment]
I rather meant the following check with "visible" / "invisible" entries, should've been clearer 😅: `if(!entry.is_visible(r.home.feed.filter,r.home.feed.target)){ continue; }`

Haven't taken a deep look yet, just wondering if a difference between the mention counter and `is_visible` could cause the mismatch.
