### ISSUE TITLE
Filtering doesn't get complete results on @username

### ISSUE THREAD

**Issue by mocknotes** [Rotonde/rotonde-client#103]
I have a feeling like this might already be a known issue and under consideration for being worked on, so apologies if this is redundant. Overall my experience with Rotonde has been very good and appreciate all the effort to bringing this project to life.

Steps to replicate:
1. Update Rotonde-client to `dat://...` in the Rotonde-portal index.html and save
2. Go to your portal and type `filter @afk` 

Expected result: Filtering gets complete results based on `@username`

When using eelfroth's Rotonde-client 0.1.44 I'm able to receive what seems like complete results when filtering on `@username` 

Here's an example of results for `@afk` on Rotonde-client 0.1.44 (result - 14 posts):
![filter-0 1 44-eelfroth-res](https://user-images.githubusercontent.com/822317/32531116-f3a9dbce-c3f6-11e7-97ed-00c44a27d78a.png)

- Forked version of eelfroth's Rotonde-client 0.1.44 where filter works as expected: dat://14d176ea25517d76979e9c24ce3cea6c690ab15bba557374df6f6989a0537255/

In version 0.1.68 I receive partial results on filtering.

Here's an example of results for `@afk` on Rotonde-client 0.1.68 (result - 3 posts):
![filter-0 1 68-neauoire-res](https://user-images.githubusercontent.com/822317/32531143-0792f9b8-c3f7-11e7-9eab-cf54eecf0725.png)

Rotonde-clients 0.1.68 which were tested and unable to get filters working:

- neauoire:  dat://2714774d6c464dd12d5f8533e28ffafd79eec23ab20990b5ac14de940680a6fe (0.1.68 result photo above)
- jimpick: dat://1a3595393282988cba62cc9c933e21a908a0b0e25e0ba083a129332436941408 (0.1.68 result photo above)
- eelfroth: dat://8606f03f7fd0a36ba2394553d8de87e2be9d194fa8599ea34fd2d3faa33080d2 (no result)
- cblgh: dat://bf1d89da157be80110e6d3f602e9dc3fd3066a513b9ef7435692bc657c89d0cb (unable to load my portal to test using this client)
- Pulled the most recent update from Github and tried using a local build of the client  (0.1.68 result photo above)

**Comment by eelfroth** [comment]
the syntax has been changed to `filter:portalname`, so when you do `filter:eelfroth` you should see all my posts (and only _from_ me, not _to_ me).
I added updating the documentation to my todo list (it keeps growing, gotta work on crossing these things off faster^^).
also, autocomplete would be nice for `filter:portalname`.

**Comment by mocknotes** [comment]
Thank you @eelfroth! Using the updated syntax `filter:portalname` works as expected.

Filtering is one of my favorite features because it makes it easy to explore Rotonde from the commander.

**Comment by eelfroth** [comment]
ok, it's in the readme now too :)
