### ISSUE TITLE
Some portals broken, apparently trying to load wrong rotonde.js

### ISSUE THREAD

**Issue by dcposch** [Rotonde/rotonde-client#105]
Beaker version: 0.7.7

### some portals are broken
example: ~kow, dat://3c14fc1b3ead41e4207a2e80c891cf4868fcf8fd007ac952f16b2bd262e0e51e/

when i visit the URL above, Beaker hangs for a long time, then I see the following error

![image](https://user-images.githubusercontent.com/169280/32574092-004ba09a-c485-11e7-9bcd-2648b74a3df3.png)

the dat itself is loading correctly--but once loaded, it tries to fetch Rotonde from the following URL, which doesn't work:

dat://87c5086498a8194c6180df9defaf4977bd5e1cc4e0343c520ea7fec8f974b21d/rotonde.js

loading that by itself:

![image](https://user-images.githubusercontent.com/169280/32574129-1c1207ba-c485-11e7-9b80-a262a080771b.png)

### possible fix

it looks like the correct URL for the latest version of Rotonde is dat://2714774d6c464dd12d5f8533e28ffafd79eec23ab20990b5ac14de940680a6fe/rotonde.js

unclear why some portals are linking to that other, broken one--but if someone still has the corresponding private key, maybe mirror  dat://2714774d6c464dd12d5f8533e28ffafd79eec23ab20990b5ac14de940680a6fe/ over to dat://87c5086498a8194c6180df9defaf4977bd5e1cc4e0343c520ea7fec8f974b21d to fix those portals ?

**Comment by eelfroth** [comment]
I can reach dat://87c5086498a8194c6180df9defaf4977bd5e1cc4e0343c520ea7fec8f974b21d fine! It appears to be a fork of rotonde-client 0.1.68. there were probably no seeds when you tried.

**Comment by dcposch** [comment]
that makes sense. i'm running my own version of rotonde-client as well (but i'm replicating it on a server, so that my Rotonde feed always stays available).

it's a bad user experience for profile links to randomly hang and fail to resolve

also, loading a new rotonde instance from scratch is sloooww, even on my fast internet--so even when a profile link does work, it's not quick

### idea ~ follow profile links without a page refresh

in other words, if i'm on my own Rotonde ( dat://rotonde-dcposch.hashbash.io ) and i follow a link, instead of going to `dat://3c14fc1...`, the link would go to `dat://rotonde-dcposch.hashbash.io/#feed/3c14fc1...`

that way, we could probably load ~kow's posts almost instantly & regardless of whether his fork of `rotonde-client` is currently available

(this would solve other problems, as well. i'd be seeing his feed from my own perspective rather than from his perspective--so we could show eg a Follow button, like Twitter)

**Comment by 0x0ade** [comment]
https://github.com/Rotonde/rotonde-client/commit/fb6dccda2e044c285cebc1ca0d67bf2685f6d60a changes the behavior when clicking on someone's name / icon. Instead of opening their portal page, Rotonde now displays their posts on your page.

I assume this solves the issue :)
