### ISSUE TITLE
Beaker Browser crashing a ton after 0.1.8 rotonde update

### ISSUE THREAD

**Issue by frozenpandaman** [Rotonde/rotonde-client#114]
Think it has to do with the discovery phase of loading (populating the rightmost tab) as it always crashes during this phase. Can't even load my own userpage half of the time (only stays open for ~10-15 secs before crashing).

**Comment by eelfroth** [comment]
so it crashes at 'Connecting to 0/X portals… 0%` (message in the operatior)?

**Comment by frozenpandaman** [comment]
Usually it loads around 10-20 of em before crashing… sometimes even all of them without issue, but I'd say 80% of time it crashes Beaker Browser at some point during that "connecting…" process/phase.

**Comment by pfrazee** [comment]
We are *so close* to releasing a new Beaker with the crash fix. Very very soon.

**Comment by frozenpandaman** [comment]
Awesome, thanks for the update @pfrazee. :)

**Comment by neauoire** [comment]
Fixed!!!!!

**Comment by frozenpandaman** [comment]
Woo!
