### ISSUE TITLE
Discussion: Make onboarding easier with index.html in rotonde-client

### ISSUE THREAD

**Issue by 0x0ade** [Rotonde/rotonde-client#117]
Moving over the post-merge discussion from #116

@neauoire:
> I was thinking about adding an index.html page to the client repo with on boarding instructions, what do you think?

⁣

@0x0ade:
> I welcome a index.html page with on boarding instructions... but I'm wondering: Is it possible to modify the DatArchive created by DatArchive.fork(url)? If so, we could just create a "create portal" button

⁣

@webdesserts:
> I already made something like this (doesn't modify the svg atm). Got caught up with work and never announced it: dat://af5ef11cdb370a641bf9a95854b74f42bf445e84969c05968f5385f7cde7487d/

> I'll work on adding an svg upload today.

**Comment by webdesserts** [comment]
Published the [git repository](https://github.com/webdesserts/rotonde-launchpad). I'll make modifications there for now. If y'all want to pull it into the Rotonde org, feel free to fork/re-publish etc. I did want to eventually combine this with louis' guide in some way.

**Comment by webdesserts** [comment]
Ok, the site now has a default svg to replace @neauoire's whenever you create the portal and also allows you to upload your own. One thought is that this could also be re-purposed to "update" someone's information later. Use `DatArchive.selectArchive()`, read in the `portal.json`, allow them to edit and then save back to the site. This would allow us to offload the bulk of the "settings" ui & logic to an exterior site.

**Comment by webdesserts** [comment]
ohh! You could skip `DatArchive.selectArchive()` if we do something like

```
<a href="dat://rotonde-settings.hashbase.io?dat%3A%2F%2F2f21e3c122ef0f2555d3a99497710cd875c7b0383f998a2d37c02c042d598485%2F">Preferences</a>
```
or even just use `document.referrer`

**Comment by neauoire** [comment]
Added to Rotonde org!

**Comment by neauoire** [comment]
Could we actually merge this with the client? And have this run as the index.html?

**Comment by webdesserts** [comment]
@neauoire Sure, I'd be up for workin' on that this weekend if y'all want me to.

**Comment by neauoire** [comment]
I'm available too! If you migrate it on the main repo as a PR, I might tweak the design a bit :) I'll also put in the default icon.

**Comment by webdesserts** [comment]
@neauoire Mmmmk. Sounds good to me.

**Comment by webdesserts** [comment]
I've opened a PR here: #123

**Comment by neauoire** [comment]
That's pretty much solid, closing.
