### ISSUE TITLE
Feature Discussion: Back to my site

### ISSUE THREAD

**Issue by kodedninja** [Rotonde/rotonde-client#128]
What I'm really missing is the possibility to go to my site from another one with one click. Now I have to do this either with the Back button in Beaker, or I must open the other site in a new tab. 

Possible solution:  saving a cookie with the url of your site and showing a link with that on every other site.

Opinions?

**Comment by 0x0ade** [comment]
We can't access cookies from another domain. And even if we could (something coming to my mind: iframes as "proxy"), we'd need to choose upon a central domain to use.

I think it's better to wait for Beaker 0.8's app functionality - then we could just link to app://rotonde, which should be the current user's portal. They can still change the app name, but we shouldn't care about that.

**Comment by kodedninja** [comment]
Didn't know about that feature. You're right. 😄
