### ISSUE TITLE
Bug: attribution of entries in threads appears to be buggy?

### ISSUE THREAD

**Issue by saulhardman** [Rotonde/rotonde-client#167]
As you can see in the example below, @jimpick's entry has been attributed to @neauoire somehow.

<img width="718" alt="screen shot 2017-12-03 at 21 45 04" src="https://user-images.githubusercontent.com/578381/33529608-6d0f17d2-d873-11e7-83d3-cb281e8d1489.png">

**Comment by saulhardman** [comment]
Can anyone confirm this for me?

**Comment by webdesserts** [comment]
I was seeing similar thread weirdness the other day

**Comment by neauoire** [comment]
Fixed by @kodedninja

**Comment by kodedninja** [comment]
@neauoire I don't think so :smile: the one I fixed is that you weren't able to quote yourself. Or are these related?

**Comment by neauoire** [comment]
Oh, I misread what the new code was doing. I'll have a look at this one then 👍

**Comment by jimpick** [comment]
Another example:

<img width="685" alt="screenshot 2017-12-07 07 00 33" src="https://user-images.githubusercontent.com/20886/33721732-baa1200c-db1c-11e7-84ad-3bbd1a3bfe46.png">
