### ISSUE TITLE
user's "site" doesn't require protocol

### ISSUE THREAD

**Issue by frozenpandaman** [Rotonde/rotonde-client#17]
If I set my site (`edit:site`) to `twitter.com/frozenpandaman`, clicking on the URL in my sidebar will simply append the text to my dat:// URL, i.e. `dat://1327c...69838/twitter.com/frozenpandaman`, giving a 404.

It seems if a protocol, e.g. https://, is given, it hides it in the HTML but keeps it in the rendered `a href` tag, i.e. just shows `twitter.com/frozenpandaman` but the link still works correctly. (I like this!)

The `site` field should support dat:// URLs too, of course, but when setting/editing it, it should probably default to http:// if no protocol is given.

**Comment by underscorediscovery** [comment]
That should do it, the idea of default to http makes sense and that's what it does now.

**Comment by frozenpandaman** [comment]
looks good @underscorediscovery. :) thanks!
