### ISSUE TITLE
Entire `.git` folder is distributed via Dat

### ISSUE THREAD

**Issue by saulhardman** [Rotonde/rotonde-client#29]
This is the case for both the client and the portal:

- `rotonde-client` instance: `dat://fab5c8f60ac249ccb22e2abf650a8f7f15907aff05c4a5f3140be6abdf5c60bf/.git/`
- `rotonde-portal` instance: `dat://809b8c277bbdaa05d47ade6aab2f10345b9999208f0ff73ac8eff24c0988011e/.git/`

Before submitting a fix (adding the `.git` to the `.datignore` files in both repositories) I just wanted to make sure that this wasn't being done for a reason? Because Dat depends on it, for example.

**Comment by noformnocontent** [comment]
i dont think dat needs `.git/`, it has its own versioning outside of seeding folders, you could have plain `dat.json` and hand-edited `portal.json` and it would be enough to partake in write-only rotonde (bots for example)

**Comment by saulhardman** [comment]
Thanks for the information @noformnocontent, can you see those `.git` folders that I linked by the way? It would appear to me as though you can only see them on your own sites 🤔

**Comment by noformnocontent** [comment]
hm, no, i can see .DS_Store though what version are you on?

maybe `.git/` (and `.svn/` and such) included in ignore-presets of beaker itself?

**Comment by saulhardman** [comment]
I think Beaker is preventing access to the `.git` directory if you're not the site owner.

Even so, is it worth adding `.git` to the `.datignore` file?

I'm on the latest version (as of now). The additions of `.DS*` to the ignore files doesn't work retrospectively on Dat it would appear.

**Comment by webdesserts** [comment]
Seems like `dat` is supposed to [ignore dot files and folders](https://github.com/datproject/dat#ignoring-files). So not sure how the `.DS_Store` managed to get in there.

**Comment by composition4** [comment]
...perhaps through `dat sync` or `dat share`; some testing may be needed before submitting a PR to them.
