### ISSUE TITLE
How does seeding factor into portal availability?

### ISSUE THREAD

**Issue by saulhardman** [Rotonde/rotonde-client#31]
I'm new to Dat and peer-to-peer protocols so please bear with me 🙇

For most portals, I can quite easily tell if a portal owner is offline by the absence of their name in the portal list and their entries in my feed. And it can be confirmed by navigating to their Dat URL and seeing that their portal is unavailable. This tells me that the robustness of our network isn't particularly good and it got me wondering why.

The first issue is one of seeding portals. Am I correct in presuming that a 'follow' does not equate to a 'seed'? If not, could we prompt users to seed a portal once they begin following?

The second issue (introduced with the new split portal/client architecture) relates to the client Dat site. The availability of our portal sites is dependent on our client sites, but we don't encourage users to broadcast the URL of the latter in order for those to be seeded. So, even if the availability of my portal is high, if I'm the only 1 seeding my client site and I go offline, then the portal does too.

Is this accurate? What can we do to remedy the situation and improve the availability of portals?

Side note: when I first heard about this split architecture, I presumed that there would be a single client Dat site that the majority of users would direct their portals to. This would be managed by the OSS stewards, highly seeded, and (hopefully) always available. But now every user has both a portal and a client, was this the intended outcome?

**Comment by lsjroberts** [comment]
> The first issue is one of seeding portals. Am I correct in presuming that a 'follow' does not equate to a 'seed'? If not, could we prompt users to seed a portal once they begin following?

Yeah you would need to add their dat to your library to seed it. I don't know if there is a Beaker API to do that outside of the browser UI itself. But we could at a minimum still guide the user to it.

Not sure on your second and third points.

**Comment by deamme** [comment]
So when you follow someone you don't actually seed anything. What happens is that you're just adding a new portal(user) to your portal.json. So to keep your site 'alive' you need to use something like hashbase.io that will seed the site for you and you can go offline and everyone else can still visit your site.

The split architecture is for your convenience. Changes is constantly being made for `rotonde-client` to improve the client (git pull this frequently) . The `rotonde-portal` is for your own use to customize your profile by e.g. setting up your initial portals that you want to follow etc.

**Comment by lsjroberts** [comment]
> I presumed that there would be a single client Dat site that the majority of users would direct their portals to. This would be managed by the OSS stewards, highly seeded, and (hopefully) always available.

This does seem to be the default behaviour suggested in the README and also from [Louis's tutorial](http://louis.center/p2p-social-networking/). Both of which just talk about forking the `rotonde-portal` site.

**Comment by saulhardman** [comment]
Ah, that's different to the instructions that I read when I did the migration to the 2-site setup. So does that mean that we should all be linking to this URL in our portals and seeding it as the universal `rotonde-client`, site locally and on hashnode?

`dat://2714774d6c464dd12d5f8533e28ffafd79eec23ab20990b5ac14de940680a6fe/`

(I extracted that from @neauoire's portal).

**Comment by deamme** [comment]
Yes I think that's what the plan is for now. @neauoire  is the sole owner of that dat so we need to trust that source which is a problem in itself when the network shouldn't rely on one person.

**Comment by webdesserts** [comment]
@deamme I don't see that as an issue. I don't think Rotonde could ever be a trustless system, there's always going to be a steward of the code. If you don't trust @neauoire, then you can always host your own client and use that instead, it would have lower availability most likely, but it would still work. If @neauoire and @cblgh dropped off the face of the earth, the dat would still exist as long as someone is seeding it. People in the community could fork, update their portals and move on. Unlike twitter etc, all the data still lives in the user sites, Rotonde just helps you browse and manage it.

Dat currently doesn't allow multi-writers. I believe that was something they were working on. If that comes to fruition i would expect a small group in the Rotonde org could be designated as writers. However, it would just be the difference of trusting a small group of people vs one person though. In my mind the project is so young that a BDFL (or set thereof) is probably preferable to keep the project focused.

**Comment by webdesserts** [comment]
I do think that Rotonde could probably encourage seeding of the client a little bit more, whether it's a note in the documentation or by some other means.

**Comment by neauoire** [comment]
Wait, no that's the opposite of what this should be haha. Host your own client if you like, or fork it and change it. Don't rely on my client to be online, nor up to date. This is just for onboarding :)

**Comment by neauoire** [comment]
The idea behind this scheme is that by forking a frontend you're almost assured that that client is active, in time I'm thinking that clients might diverge but preserve the same data structure it being mobile clients or other purposes.

**Comment by pfrazee** [comment]
Beaker uses a default policy of "seed on read." That means that, when you access a Dat, you're going to enter its swarm to both download & upload files. After a period of no access, Beaker will leave the swarm for the Dat. This is the policy that's currently keeping the Rotonde network online. It's kind of a 'viral availability' system.

One thing that's worth noting about "seed on read" is that Beaker only downloads the files it needs from Dats. That means you'll only be able to seed the files you download as well. @louiscenter there's a *chance* that's why you were having trouble forking the other day; it's possible the full Dat was't being seeded by anybody.

An alternative policy to "seed on read" would be the "seed all whitelist." That policy is a listing of Dats for which you download and then actively seed all contained files at all fines. That's basically most useful when you want to help somebody stay online; it's kind of altruistic share mode. We want to make the "seed all whitelist" available as an API in future Beaker versions, and we'll have some version of it available in 0.8.

I would bet that we'll get better portal availability once seed-all policies are in Beaker, and can be used by applications.
