### ISSUE TITLE
Direct Messages

### ISSUE THREAD

**Issue by jyng** [Rotonde/rotonde-client#39]
is there a plan for direct messages to users? or is that something out of scope?

**Comment by neauoire** [comment]
Definitely not out of scope, would definitely merge to the client if someone implemented that!
So many people want this, a lot of users would be quite happy. Have a look into multi-writer or the thread on Rotonde Services and custom.js

**Comment by neauoire** [comment]
I had 15 minutes available and implemented `whispers`, you can send a direct message, invisible to others with `whisper:neauoire psst!`.

**Comment by pfrazee** [comment]
You should make sure people know that whispers aren't encrypted. You'll be able to read them by looking at somebody's portal.json.

**Comment by neauoire** [comment]
Yeah, that's .. I mean. 
I hope people understood that with Rotonde, maybe we should be more explicit that when you download someone's JSON file, you can actually open it in a text editor and look at it. The purpose of the whisper is more to create rapid answers that do not require public response/presence.

**Comment by pfrazee** [comment]
KK yeah dont mind me just wanted to be sure

**Comment by jyng** [comment]
wow, i did not expect to come back to see this feature implemented. props to you @neauoire

**Comment by frozenpandaman** [comment]
@neauoire 

testing whispers on 0.1.41. i mentioned @alphaflood but their username doesn't seem to appear… i just see `@eli &   `

![image](https://user-images.githubusercontent.com/7245874/31806101-a15ab0c2-b51a-11e7-99a6-d0dd9fadc993.png)

**Comment by frozenpandaman** [comment]
446352c fixes it! (note it doesn't retroactively fix old ones, though). thanks @neauoire!

![image](https://user-images.githubusercontent.com/7245874/31806393-53cb95f4-b51c-11e7-84a4-1fd9f3f4e5b1.png)

they now show up on my page/feed too, which is good. :)
