### ISSUE TITLE
Rotonde & Hashbase

### ISSUE THREAD

**Issue by jyng** [Rotonde/rotonde-client#48]
I'm having problems getting the https version (via hashbase) of rotonde working. 
When I go here: https://rotonde-earthperson.hashbase.io, I get a blank page. So I think the site is live, but maybe rotonde is not configured for hashbase?

I thought that I had to direct to the index.html in the link, but that gave me the same result.

Is anyone else experiencing this issue?

**Comment by neauoire** [comment]
This is probably a very *very* silly question but, you're trying to load this through the Beaker browser, right?

**Comment by jyng** [comment]
Ah no silly questions! If anything I'm the silly one, haha. 

I'm mainly trying to load through Chrome.
dat://rotonde-earthperson.hashbash.io works fine in Beaker. https://rotonde-earthperson.hashbase.io gives me the same result on Chrome & Beaker.

**Comment by neauoire** [comment]
Rotonde uses a couple of Beaker APIs, to load content from the distributed network, it will probably crash when Chrome tries to load DatArchive() objects and so on. It's unlikely that Chrome will support the dat: protocol.

**Comment by jyng** [comment]
ahhh okay. so would you say, it is intentional that the only way to view rotonde is through beaker (or via p2p)?

**Comment by neauoire** [comment]
Mhmm, it's intentional in the sense that it's the only browser that supports the functionality that we need to make this sort of project happen. While it might look like Twitter from the outside, it shares almost nothing with it under the hood.

**Comment by jyng** [comment]
Ah i see i see. Thanks for the clarity.

**Comment by jyng** [comment]
This issue can be closed now :)

**Comment by neauoire** [comment]
Alright :) don't hesitate to ask anything!
