### ISSUE TITLE
Accidental bug with quote, that actually might be a feature

### ISSUE THREAD

**Issue by neauoire** [Rotonde/rotonde-client#49]
I noticed that the quote message contained the message being quoted, and the message that it quoted, and that other message that this quoted message quoted. We should either, get rid of the thread, as it might lead to larger portal files, or use this to show the whole thread via an **expand** button or something. Food for thoughts.

**Comment by frozenpandaman** [comment]
it's quotes all the way down…

**Comment by karloscarweber** [comment]
This is totally a feature. I say we do what you just suggested.

**Comment by neauoire** [comment]
Keeping as is.
