### ISSUE TITLE
cicking on timestamp publicly quotes whisper

### ISSUE THREAD

**Issue by frozenpandaman** [Rotonde/rotonde-client#54]
[example screenshot here](https://user-images.githubusercontent.com/7245874/31807885-7943300e-b525-11e7-9363-96831d9f320e.png)

if i click on the timestamp of a whisper to me, i'm able to quote the post, essentially making the original post text public. perhaps clicking on the timestamp should autofill with `whisper:username` instead of `quote:username-#`?

**Comment by aeonofdiscord** [comment]
PR up for this: https://github.com/Rotonde/rotonde-client/pull/60

**Comment by frozenpandaman** [comment]
good branch name
