### ISSUE TITLE
Unable to filter on your own posts

### ISSUE THREAD

**Issue by mocknotes** [Rotonde/rotonde-client#65]
In the past it was possible was to revisit posts you made in the past by filtering on your own username `filter @my_username` and then you could see your posts.  

Now, it shows: 
> Fetching # feeds...

and doesn't complete the fetch.  

An edge case that seems related. If your Rotonde is not following anyone you are unable see your posts. It displays fetching and doesn't complete the fetch.

Filtering on others usernames works as expected.

**Comment by eelfroth** [comment]
`filter @my_username` works fine for me

**Comment by mocknotes** [comment]
Thanks for testing @eelfroth!

I updated the index.html to point at your client dat and filtering works as expected. `dat://8606f03f7fd0a36ba2394553d8de87e2be9d194fa8599ea34fd2d3faa33080d2/` 

Previously, I was pointing at the dat on [github repo](https://github.com/Rotonde/rotonde-portal/blob/master/index.html).

If not too much trouble, would it be possible to re-test `filter @my_username` after updating  rotonde-portal/index.html to: `dat://2714774d6c464dd12d5f8533e28ffafd79eec23ab20990b5ac14de940680a6fe/`

**Comment by maribov** [comment]
just tried your dat @mocknotes , filter @myname works for me w it

**Comment by mocknotes** [comment]
Thank you @maribov!

I'm going to close the issue.
