### ISSUE TITLE
Bug: Hover on portal list stretches sidebar if username lengths are too long. Add max username length?

### ISSUE THREAD

**Issue by maribov** [Rotonde/rotonde-client#67]
I want to fix this but I think we should discuss how we'd want to approach the fix? Stretch side nav to fit username lengths? One-column list of usernames? only show first X characters of usernames to prevent stretching? Something else?

Maybe we should institute max username length to make this a simpler fix, since we aren't worried about mobile right now anyway.

edit: for what it's worth for now I just made my list of linked portals into one column, but that would still break things if someone made a sentence long username which on cursory glance of the client code seems possible?

**Comment by frozenpandaman** [comment]
>Maybe we should institute max username length to make this a simpler fix, since we aren't worried about mobile right now anyway.

I think we should probably do this. Do we also want to limit usernames to alphanumeric characters (plus maybe a few symbols)? Might be helpful just to avoid [breaking anything](https://twitter.com/fakeunicode) or malicious stuff down the line. There's already a user named @ᐱᕐᓇᑐ lol.

**Comment by eelfroth** [comment]
I think the better solution is to have the client just be able to deal with long names, cutting them short when _displaying_ them. This would not impose on what users have in their data, and different clients might choose different lengths based on layout.

I'm strongly opposed to the idea of limiting usernames to alphanumerics. I see that as a very americanocentric writing system… All languages and writing systems should be welcomed.

**Comment by frozenpandaman** [comment]
>All languages and writing systems should be welcomed.

Completely agreed! Browsers/computers/fonts are often just very bad at supporting some of the more non-standard Unicode codepoints though, e.g. a while ago certain private use characters made a major release of Chrome *crash*. So maybe relevant to address that at some point.

**Comment by maribov** [comment]
Oh yeah i definitely don't want to limit LANGUAGES, just malicious injections and weird unicode that isn't a part of any language. Like if we implement search as a standard later (and now it already exists as an extra app someone made) it will be really hard to search for someone named "five skull emojis" or something

**Comment by neauoire** [comment]
There are no more sidebars.
