### ISSUE TITLE
text formatting syntaxes only render first of each style

### ISSUE THREAD

**Issue by frozenpandaman** [Rotonde/rotonde-client#69]
only the first instance of each text formatting style renders

![image](https://user-images.githubusercontent.com/7245874/31849581-5f43fdee-b5f9-11e7-86ca-acbba63f4367.png)

**Comment by ianh** [comment]
Fixed in c397253.

**Comment by frozenpandaman** [comment]
looks good, thanks @ianh.

(what's the guideline as to when the version number gets updated? it's been 0.1.42 for a while now, but was getting changed with nearly every push yesterday. no worries, am just curious.)

**Comment by frozenpandaman** [comment]
>https://github.com/Rotonde/rotonde-client/commit/fc47966b4c241ea42e16ca376e356046269cd37f

lol 😅

**Comment by ianh** [comment]
Ah, good point, I bumped it in fc47966.  I know about as much as you about what the guidelines are!  I've just been trying to keep things running.
