### ISSUE TITLE
timestamp (uuid?) for message id

### ISSUE THREAD

**Issue by forresto** [Rotonde/rotonde-client#76]
The current index-based ids will break if items are removed or reordered.

https://www.npmjs.com/package/uuid (or the one-liner https://gist.github.com/jed/982883) could be a good way to generate unique ids for items in the feed. Then it will be easier to find quoted items in own or other's feed.

**Comment by hermes-diactoros** [comment]
I think this is important: for its own right, and because it makes conversation chains easier to program. What does @neauoire think?

**Comment by forresto** [comment]
Or link/quote with `message.timestamp`? That might be unique enough here.

**Comment by eelfroth** [comment]
> message.timestamp
agreed. if someone has two entries with the same timestamp they'd probably have edited their portal.json by hand just to do this

**Comment by forresto** [comment]
How does this (eg linking to a specific message) relate to `webdb` wip? https://github.com/Rotonde/rotonde-client/issues/41
@pfrazee?

**Comment by pfrazee** [comment]
In `webdb` each post is its own file, so you link to the file to refer to a post. I'm currently using https://github.com/nathan7/monotonic-timestamp-base36 for uuids

**Comment by 0x0ade** [comment]
We've switched to the post's filename minus the `.json` file ending as the ID. For now, all Rotonde posts have an ID equal to the timestamp. I doubt any Rotonde user will post two posts in one millisecond, unless they attempt to manipulate the post's timestamp manually.

By the way: Before the switch to the Fritter-based post and profile formats, Rotonde assumed the ID to be a number. We don't read / write posts based on an index in a list anymore, but can now use any arbitrary string without spaces as the ID. (The command parser dislikes spaces.)

I assume this issue has thus been solved.
