### ISSUE TITLE
Unable to reset rotonde profile

### ISSUE THREAD

**Issue by hermes-diactoros** [Rotonde/rotonde-client#78]
Following the steps described in [this post](https://louis.center/p2p-social-networking/), I get stuck when trying to reset my rotonde profile. I click on the command text box and press "Ctrl+Shift+Backspace", and nothing happens. After checking the console for errors, I see the following:

> rotonde.js:106 Uncaught (in promise) TypeError: Cannot read property 'archive' of null
>     at Rotonde.reset_with_name (rotonde.js:106)
>     at Rotonde.reset (rotonde.js:100)
>     at HTMLTextAreaElement.Operator.key_down (operator.js:269)
> Rotonde.reset_with_name @ rotonde.js:106
> Rotonde.reset @ rotonde.js:100
> Operator.key_down @ operator.js:269

Seems like the `archive' variable is null for some reason. Any ideas?

Using Beaker _Version: 0.7.6 Electron: 1.7.4 - Chromium: 58.0.3029.110 - Node: 7.9.0_.

**Comment by ireneuszgabrys** [comment]
I have exactly the same problem. It looks like ``this.portal`` is set to ``null`` so ``this.portal.archive`` and ``this.portal.save`` (after trying to set ``archive`` by hand) results an error.

**Comment by neauoire** [comment]
Fixed :) sorry about that.
