### ISSUE TITLE
updating rotonde?

### ISSUE THREAD

**Issue by seekr** [Rotonde/rotonde-client#80]
Jealous of all the new rotonde features I see in other's profiles. How can update rotonde without loosing my posts?

**Comment by neauoire** [comment]
You only need to keep your portal.json & your avatar.svg file. Maybe, if you don't want to maintain your own client, just fork my page, and replace my portal and avatar files with yours.

-- dat://2f21e3c122ef0f2555d3a99497710cd875c7b0383f998a2d37c02c042d598485/#neauoire-94

**Comment by eelfroth** [comment]
If you're updating from github.com/Rotonde/beaker to rotonde-portal, wouldn't it be enough to download the new index.html and replace the old one with it?
(that should be enough to get it working. to keep your portal tidy, you can then delete the obsolete folders "scripts" and "fonts", as well as all css files except the custom.css)
