### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by hermes-diactoros** [Rotonde/rotonde-client#83]
Seems like the autocomplete mention feature is not working. The problem is [this line](https://github.com/Rotonde/rotonde-client/blob/70b1991becb7aef8594950d6e794866cf8ea8dbf/scripts/operator.js#L311); there's no such function (`autocomplete_name`) in the "index" Rotonde object, which I think does not exist.

Is "index" now named "home"?

**Comment by neauoire** [comment]
Yeah I had to turn it off for the remodel. Home has some functionality of the old index toolkit. If you're up for it, you can build a list of autocomplete usernames from `r.home.feed.portals`. I'm working on re-adding the **discovery** tools, it should not interfere.

**Comment by hermes-diactoros** [comment]
**TODO:** Smarter regex matching starting at cursor position. I'll be working on it, + better mentions.

**Comment by neauoire** [comment]
It's pretty much working as expected now.
