### ISSUE TITLE
Filter command & usernames

### ISSUE THREAD

**Issue by frozenpandaman** [Rotonde/rotonde-client#85]
If I click on the mentions tab which autopopulates the commander with `filter eli`, this includes results such as posts where somebody has included the word "feeling," since this has the sequence of letters `eli` in it. While this isn't a problem if your username is something quite unique that certainly won't be embedded in the other words, I'd imagine this would be even more annoying if your username was just @a, or something short and/or common.

**Comment by neauoire** [comment]
Fixed :)
