### ISSUE TITLE
Entries with less than one hundred characters are being marked as 'large'

### ISSUE THREAD

**Issue by finnoleary** [Rotonde/rotonde-client#92]
I wasn't sure whether to PR this because I'm new to the code and I'm unsure if this is intentional.

https://github.com/Rotonde/rotonde-client/blob/cbd5be0bedf28f1b3d5a5bc120c4797bf85b2dcc/scripts/entry.js#L39

**Comment by neauoire** [comment]
I'll remove it as people thought it was useless.
